const mongoose = require("mongoose");

const PacienteSchema = new mongoose.Schema({
  nome: { type: String, required: true },
  idade: { type: Number, required: true },
  dataNascimento: { type: Date, required: true },
  endereco: {
    rua: { type: String },
    numero: { type: String },
    cidade: { type: String },
    estado: { type: String },
    cep: { type: String },
  },
  tabagista: { type: Boolean },
  alcool: { type: Boolean },
  covid: { type: Boolean },
  sequelas: { type: String },
  alergias: { type: String },
  suplementacao: { type: String },
  suplementacaoDescricao: { type: String },
  refeicoes: { type: String },
  carne: { type: String },
  lanches: { type: String },
  refrigerante: { type: String },
  frutas: { type: String },
  leite: { type: String },
  madrugada: { type: String },
  ultimoHorario: { type: String },
  horarioDorme: { type: String },
  intolerancia: { type: String },
  melasma: { type: String },
  manchas: [{ type: String }],
  linhas: [{ type: String }],
  acne: { type: String },
  grau: { type: String },
  regiaoAcne: [{ type: String }],
  cicatriz: { type: String },
  tipoCicatriz: [{ type: String }],
  olheiras: { type: String },
  tipoOlheiras: [{ type: String }],
  tratamento: {
    diagnostico: { type: String },
    descricao: { type: String },
    conduta: { type: String },
    valor: { type: String },
    data: { type: String },
    assinatura: { type: String },
    termosAceitos: {
      termo1: { type: Boolean },
      termo2: { type: Boolean },
    },
  },
  tratamentoSugerido: {
    tratamento: { type: String },
    numeroSessao: { type: Number },
    valorSessao: { type: Number },
    valorTotal: { type: Number },
    preAgendamento: { type: String },
    horario: { type: String },
  },
  contratoAssinaturas: [
    {
      contratanteAssinatura: { type: String },
      contratadaAssinatura: { type: String },
    },
  ],
  patologias: [{ type: String }],
  funcionamentoIntestinal: { type: String },
  gestante: { type: String },
  contraceptivo: { type: String },
  cicloMenstrual: { type: String },
  ultimaGestacao: { type: String },
  qualidadeSono: { type: String },
  ansiedade: { type: String },
  nervosismo: { type: String },
  exercicio: { type: String },
  image: { type: String, required: false },
});

const Paciente = mongoose.model("Paciente", PacienteSchema);

module.exports = Paciente;
